### PR TITLE
Switch default sync mode from FAST

### PR DESCRIPTION
**Pull request by non-fungible-nelson**
FAST sync is no longer the preferred method. We have only kept the X mark for other sync modes in order to force ourselves to implement snap sync as a server.

### CODE REVIEW

**Comment by alexpeterson91** [comment]
@non-fungible-nelson i'm gonna need to add the same additional commits as i did for your PR on goerli besu.  
BTW I have a question for you about how Besu handles changing sync modes, does it need to have the db cleared to change from `FAST`, `FULL`, or `X_SNAP"  to `X_CHECKPOINT`? or any other combination?  i personally always found while helping initially write this and maintain this package that I and the original author both needed to wipe the chain data volume when trying to switch to X_SNAP when that was the cutting edge method still kinda in experimental stages.  is it it necessary to perform a full resync when switching to `X_CHECKPOINT` or any other mode? If so we would have to handle this transition very carefully and do a migration if possible and take time to spread the word to any current Besu users on any network not using X_CHECKPOINT already, we'd need to alert them that an update changing the default settings is coming and will break your node at least temporarily while it resyncs.  So it's important to know this, let me know if you do so i can make sure we do this properly.

**Review by alexpeterson91 — CHANGES_REQUESTED** [review]
I see you work at consensys so i was hoping you could give a definitive answer on changing sync methods while running, not while syncing while already synced. i.e. If I have Besu synced with `FAST` because it was default, would changing the configuration flag for `--syncmode` to `X_CHECKPOINT` cause a problem with my running fully synced install? or would it continue to function all the same and only behave differently if it falls out of sync or has its volume wiped manually?  Same storage structure Bonsai. just different sync method when already synced.  thanks

**Comment by non-fungible-nelson** [comment]
Hey confirmed this with some tests, no issues (with Teku):
* Stop / modify sync type from Fast to X_SNAP / start :white_check_mark:
* Stop / modify sync type from Fast to X_SNAP / wait 10 minutes / start :white_check_mark:
* Stop / modify sync type from Fast to X_SNAP / wait 1 hour / start :white_check_mark:
* Stop / modify sync type from Fast to X_SNAP / delete teku database / start :white_check_mark: (Backward sync)

**Comment by alexpeterson91** [comment]
> Hey confirmed this with some tests, no issues (with Teku):
> 
> * Stop / modify sync type from Fast to X_SNAP / start ✅
> * Stop / modify sync type from Fast to X_SNAP / wait 10 minutes / start ✅
> * Stop / modify sync type from Fast to X_SNAP / wait 1 hour / start ✅
> * Stop / modify sync type from Fast to X_SNAP / delete teku database / start ✅ (Backward sync)
> 
> Checkpoint sync should be the exact same, as it is slightly modified snap.
> 
> Forest to Bonsai as you mentioned does require a resync. hope this helps!

Sorry for the delay been AFK for a bit, but thanks a bunch for the info! 👍 

I need to confirm one test myself which is already teed up and ill have results real soon and then good to go to merge, Right now  I just gotta work on debugging the latest versions of besu on dappnode which arent passing CI right now, Besu is getting pretty out of date now on the dappnode side so when the new version is debugged well publish new versions (mainnet and not), and that'll include `X_CHECKPOINT` as default sync mode

**Pull request merged**
